# Generated by Django 4.2 on 2025-11-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='year_of_study',
            field=models.IntegerField(blank=True, choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5'), (6, 'Year 6')], default=1, null=True, verbose_name='Year of Study'),
        ),
    ]
