# Generated by Django 4.2 on 2025-12-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_sharing', '0002_studentdata_year_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='virtual_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
