# Generated by Django 4.2 on 2025-12-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_sharing', '0003_studentdata_virtual_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for this notice (optional)', null=True, upload_to='notices/%Y/%m/%d/'),
        ),
    ]
